version: '2'
services:
  myretail:
    build: .
    environment:
      - server_port=8082
      - spring_data_mongodb_host=mongodb
      - spring_data_mongodb_port=27017
      - spring_data_mongodb_database=myretail
      - myretail_product_url=https://redsky.target.com/v2/pdp/tcin/%d?excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics
      - myretail_product_timeout=20000
      #- myretail.product.url=http://localhost:8082/dummy/%d
    depends_on:
      - mongodb
    ports:
      - "8082:8082"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"